[package]
name = "auditorium"
version = "0.1.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/someotherself/auditorium"
documentation = "https://docs.rs/auditorium/latest/auditorium/"
description = "High-level audio library for playback and capture"
categories = ["multimedia::audio", "multimedia"]
keywords = ["audio", "miniaudio", "playback", "recording", "dsp"]

[dependencies]
crossbeam-channel = "0.5.16"
maudio = { version = "0.1.12", features = [ "external-lib" ] }
symphonia = { version = "0.6.0", features = ["all"] }

[build-dependencies]
maudio = { version = "0.1.11", features = ["external-lib"] }